name: Release ci
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Archive config
        run: make archive

      - name: Debug info
        run: |
          git log -4
          git describe --tags --abbrev=0
          git describe --abbrev=0
          ls -la release/*

      - name: Build changelog
        uses: mikepenz/release-changelog-builder-action@v1
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*.zip"
          draft: true
          body: |
            ${{ steps.changlog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
